#!/bin/bash

jobNumber=${SLURM_ARRAY_TASK_ID}
export frstEvt=${1}
export Nevt=${2}
energy=${3}
bmin=${4}
bmax=${5}
finalOutputDir=${6}
seedBase=${7}

amptdir=$AMPT_DIR
export amptrundir=$AMPT_DIR/../ampt-run
#The format of the folder name is important:
#if you change this, change also inside_container_standalone_ampt.sh
export amptTempDir=${TMPDIR}/ampt_job_${jobNumber}

mkdir -p ${amptTempDir}/ana
cp -a ${amptdir}/. ${amptTempDir}
cd $amptTempDir

export seed=$((seedBase+jobNumber))
sed -i "1s/.*/${energy}     ! EFRM (sqrt(S_NN) in GeV if FRAME is CMS)/" input.ampt
sed -i "9s/.*/${Nevt}     ! NEVNT (total number of events)/" input.ampt
sed -i "10s/.*/${bmin}     ! BMIN (mininum impact parameter in fm)/" input.ampt
sed -i "11s/.*/${bmax}     ! BMAX (maximum impact parameter in fm, also see below)/" input.ampt
sed -i "28s/.*/0     ! ihjsed: take HIJING seed from below (D=0) or at runtime(11)/" input.ampt
sed -i "29s/.*/${seed}     ! random seed for HIJING/" input.ampt

time=$(date)
echo "Start time : $time"

echo "Executing job number ${jobNumber} with seed ${seed}.."


#Tähän tulee singularity-juttuja, nää alemmat vois ehkä laittaa insidecontainer tiedostoihin.

# Settings for singularity:
export SINGULARITY_BIND="/projappl/project_2003583,/scratch/project_2003583,$TMPDIR"
export SINGULARITY_SHELL="/bin/bash --norc"
export SINGULARITY_CACHEDIR=$TMPDIR

singularity exec --home $HOME --workdir $TMPDIR /projappl/project_2003583/alidockSingularity_alisw-slc7_21_09_20.sif /projappl/project_2003583/simO2/runningO2/ampt-standalone-run/inside_container_standalone_ampt.sh

rm ${amptTempDir}/ana/ampt.dat

singularity exec --home $HOME --workdir $TMPDIR /projappl/project_2003583/alidockSingularity_alisw-slc7_21_09_20.sif /projappl/project_2003583/simO2/runningO2/inside_container_ampt.sh




echo "Done!"

time=$(date)
echo "End time : $time"

jobNumFormat=$(printf "%02d" ${jobNumber})

mv ${amptTempDir}/ana/ampt.root ${finalOutputDir}/ampt-output${jobNumFormat}.root

rm -r $amptTempDir
rm ampt${jobNumber}.dat
