#!/bin/bash

#Setup arguments (those with export are needed inside containers)
jobNumber=${SLURM_ARRAY_TASK_ID}
export frstEvt=${1}
export Nevt=${2}
energy=${3}
bmin=${4}
bmax=${5}
export dir=${6}
export dirDigit=${7}
seedBase=${8}

#Setup dirs
amptdir=$AMPT_DIR
export amptrundir=$AMPT_DIR/../ampt-standalone-run
#The format of the folder name is important:
#if you change this, change also inside_container_standalone_ampt.sh
export amptTempDir=${TMPDIR}/ampt_job_${jobNumber}

#Create temp dir in fast disc and move AMPT there
mkdir -p ${amptTempDir}/ana
cp -a ${amptdir}/. ${amptTempDir}
cd $amptTempDir

export seed=$((seedBase+jobNumber))
sed -i "1s/.*/${energy}     ! EFRM (sqrt(S_NN) in GeV if FRAME is CMS)/" input.ampt
sed -i "9s/.*/${Nevt}     ! NEVNT (total number of events)/" input.ampt
sed -i "10s/.*/${bmin}     ! BMIN (mininum impact parameter in fm)/" input.ampt
sed -i "11s/.*/${bmax}     ! BMAX (maximum impact parameter in fm, also see below)/" input.ampt
sed -i "28s/.*/0     ! ihjsed: take HIJING seed from below (D=0) or at runtime(11)/" input.ampt
sed -i "29s/.*/${seed}     ! random seed for HIJING/" input.ampt

time=$(date)
echo "Start time : $time"

echo "Executing job number ${jobNumber} with seed ${seed}.."

# Settings for singularity:
export SINGULARITY_BIND="/projappl/project_2003583,/scratch/project_2003583,$TMPDIR"
export SINGULARITY_SHELL="/bin/bash --norc"
export SINGULARITY_CACHEDIR=$TMPDIR

export currentDir=$(pwd)

singularity exec --home $HOME --workdir $TMPDIR /projappl/project_2003583/alidockSingularity_alisw-slc7_21_09_20.sif /projappl/project_2003583/simO2/runningO2/ampt-standalone-run/inside_container_standalone_ampt.sh

echo "Done!"

#$TMPDIR will be removed automatically
#rm -r $amptTempDir

time=$(date)
echo "End time : $time"
